### ISSUE TITLE
Payment tab disabled after clicking of login tab

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-lightbox#18]
When not logged in, clicking on the login tab, disables the first tab (Payment)

![screen shot 2015-06-23 at 14 05 40](https://cloud.githubusercontent.com/assets/701331/8305621/1ea77b80-19b1-11e5-9d27-db22e866da69.png)

**Comment by handijk** [comment]
Cannot reproduce after the lightbox related tasks are added
